export const GET_CENAME_API = "GET_CENAME_API";
export const GET_CINAME_ITEMS_API = "GET_CINAME_ITEMS_API";
export const GET_INFO_CINAME_ITEMS = "GET_INFO_CINAME_ITEMS";
export const GET_LIST_FILMS_ID_CINAME = "GET_LIST_FILMS_ID_CINAME";
export const GET_CINAME_LIST_MOVIE = "GET_CINAME_LIST_MOVIE";