export const GET_SPECIES_USER_API = "GET_SPECIES_USER_API";
export const GET_USER_LOGIN_API = "GET_USER_LOGIN_API";
export const GET_USER_INFO_API = "GET_USER_INFO_API";
export const GET_UPDATE_USER_API = "GET_UPDATE_USER_API";

export const GET_USER_LOGOUT = "GET_USER_LOGOUT";
export const REG_USER_ERROR = "REG_USER_ERROR";

export const SET_TYPE_PAGE = 'SET_TYPE_PAGE';
export const SET_REQUEST_PAGE_LOGIN ="SET_REQUEST_PAGE_LOGIN";
export const SET_REQUEST_PAGE = "SET_REQUEST_PAGE";
export const RESET_INFO = "RESET_INFO";